server:
  port: 8060

management:
  port: 8080

spring:
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8085

gcp:
  project-id: test-project
  pubsub:
    person-liked-subscription-id: person-liked-subscription-id